echo Start make ha.tar
tar cvf ha.tar *.html
tar rvf ha.tar kangel.js
tar rvf ha.tar images/*.gif
tar rvf ha.tar images/*.jpg
tar rvf ha.tar images/*.png
tar rvf ha.tar *.au
tar rvf ha.tar *.ico
tar rvf ha.tar applets/*.java
tar rvf ha.tar *.css
echo End make ha.tar
